### ISSUE TITLE
The package does not extend the types for assert and expect packages

### ISSUE THREAD

**Issue by mrmlnc** [japa/snapshot#1]
### Package version

2.0.1

### Describe the bug

I get a compilation error when using the `@japa/snapshot` package for the code below:

```ts
import '@japa/assert';
import '@japa/snapshot';

import { test } from '@japa/runner';

test('test', async ({ assert }) => {
	assert.snapshot('1').match();
});
```

It looks like this package does not import [this module](https://github.com/japa/snapshot/blob/main/src/types/extended.ts) and [the types are not bundled](https://unpkg.com/@japa/snapshot@2.0.1/build/index.d.ts).

**Comment by Julien-R44** [comment]
Thanks for the issue! Fixed with latest release
