### ISSUE TITLE
The package.json file does not contain main field

### ISSUE THREAD

**Issue by mrmlnc** [japa/snapshot#2]
### Package version

2.0.1

### Describe the bug

Looks like the `package.json` file does not contain the `main` field:

```js
"main": "./build/index.js",
```

Technically, it's not a bug, but it creates frustrations for some tools. For example, one of plugins for ESLint cannot determine the path to a module within this package:

```js
Unable to resolve path to module '@japa/snapshot'.eslint[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.29.0/docs/rules/no-unresolved.md)
```

Also, this field is present in all `@japa/*` packages except this one.

Adding the `main` field solves the problem.

**Comment by Julien-R44** [comment]
Nice catch, thanks
