### ISSUE TITLE
Cannot open the discussion for the new feature

### ISSUE THREAD

**Issue by mrmlnc** [japa/snapshot#3]
### Package version

2.0.1

### Describe the bug

I would like to suggest adding the ability to specify the path to the directory for snapshots in options. I wanted to do this via discussion as [the manual says](https://github.com/japa/.github/blob/main/docs/CONTRIBUTING.md#creating-pull-requests).

However, [the current page for creating issues](https://github.com/japa/snapshot/issues/new/choose) does not allow me to do so ([image](https://github.com/japa/snapshot/assets/7034281/d5f8bad7-6bd4-412d-b11d-58eb64bc6b00)). Because it's a link to a repository (different from this one) that has no discussions.

```
https://github.com/japa/runner/issues/new?title=Discussion%20for%20a%20new%20feature%20-%20%3CYOUR%20FEATURE%20NAME%3E
```

Marked this as a bug, as I don't see any other way to communicate.

**Comment by Julien-R44** [comment]
@thetutlage will be able to tell what we should do here. Probably open a discussion forum like on the Adonis organisation?

In the meantime, feel free to open a feature request on this repo if needed.

---

The ability to specify a directory path is something we already have, via `resolveSnapshotPath`, see: https://japa.dev/docs/plugins/snapshot#configuration-options

**Comment by thetutlage** [comment]
I think we can use the AdonisJS discussions forum for the same. We even have a Japa category there for the same. https://github.com/adonisjs/core/discussions/categories/japa
